<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserAccount extends Model
{

    protected $fillable = [
        'name', 'email',
    ];

    //Define the search key field
    //For example: field name of UserAccount model
    public function getRouteKeyName()
    {
        return 'name'; // TODO: Change the autogenerated stub
    }
    public function partner()
    {
        return $this->belongsTo('App\Models\UserPartner', 'partner_id', 'id');
    }
}
